cursor #fefefe
cursor_text_color #cbccd1

foreground            #fefefe
background            #181a20
selection_foreground  #16161e
selection_background  #777a7f
url_color             #1a9fff

color0   #181a20
color1   #ff1f58
color2   #19ff36
color3   #fff003
color4   #008cf2
color5   #004476
color6   #1a9fff
color7   #e3f3ff
color8   #8f9ca5
color9   #ff5388
color10  #5eff72
color11  #fff55e
color12  #3cadff
color13  #5ebbff
color14  #97d3ff
color15  #f3faff
